namespace LookupTableEditor
{
    public static class ParametersUnitType
    {
        // csharpier-ignore-start
        public static Dictionary<string, string> GetDictionaryToConvertParamTypeInSizeTableHeaderString2020()
        {
            Dictionary<string, string> dict = new Dictionary<string, string>
            {
                { "YesNo", "##NUMBER##GENERAL" },
                { "WireSize", "##WIRE_SIZE##MILLIMETERS" },
                { "WeightPerUnitLength", "##WEIGHT_PER_UNIT_LENGTH##KILOGRAMS_FORCE_PER_METER" },
                { "Weight", "##WEIGHT##KILONEWTONS" },
                { "URL", "##OTHER##" },
                { "WarpingConstant", "##WARPING_CONSTANT##CENTIMETERS_TO_THE_SIXTH_POWER" },
                { "Volume", "##VOLUME##CUBIC_METERS" },
                { "UnitWeight", "##UNIT_WEIGHT##KILONEWTONS_PER_CUBIC_METER" },
                { "TimeInterval", "##TIMEINTERVAL##SECONDS" },
                { "ThermalExpansion", "##THERMAL_EXPANSION_COEFFICIENT##INVERSE_DEGREES_CELSIUS" },
                { "Text", "##OTHER##" },
                { "SurfaceArea", "##SURFACE_AREA##SQUARE_METERS_PER_METER" },
                { "StructuralVelocity", "##VELOCITY##METERS_PER_SECOND" },
                { "StructuralFrequency", "##STRUCTURAL_FREQUENCY##HERTZ" },
                { "Stress", "##STRESS##MEGAPASCALS" },
                { "Speed", "##SPEED##KILOMETERS_PER_HOUR" },
                { "Slope", "##SLOPE##SLOPE_DEGREES" },
                { "SectionProperty", "##SECTION_PROPERTY##CENTIMETERS" },
                { "SectionModulus", "##SECTION_MODULUS##CUBIC_CENTIMETERS" },
                { "SectionDimension", "##SECTION_DIMENSION##CENTIMETERS" },
                { "SectionArea", "##SECTION_AREA##SQUARE_CENTIMETERS" },
                { "Rotation", "##ROTATION##RADIANS" },
                { "ReinforcementVolume", "##REINFORCEMENT_VOLUME##CUBIC_CENTIMETERS" },
                { "ReinforcementSpacing", "##REINFORCEMENT_SPACING##MILLIMETERS" },
                { "ReinforcementLength", "##REINFORCEMENT_LENGTH##MILLIMETERS" },
                { "ReinforcementCover", "##REINFORCEMENT_COVER##MILLIMETERS" },
                { "ReinforcementAreaPerUnitLength", "##REINFORCEMENT_AREA_PER_UNIT_LENGTH##SQUARE_CENTIMETERS_PER_METER" },
                { "ReinforcementArea", "##REINFORCEMENT_AREA##SQUARE_CENTIMETERS" },
                { "Pulsation", "##PULSATION##RADIANS_PER_SECOND" },
                { "PipingVolume", "##PIPING_VOLUME##LITERS" },
                { "PipingViscosity", "##PIPING_VISCOSITY##PASCAL_SECONDS" },
                { "PipingVelocity", "##PIPING_VELOCITY##METERS_PER_SECOND" },
                { "PipingTemperatureDifference", "##PIPING_TEMPERATURE_DIFFERENCE##CELSIUS_DIFFERENCE" },
                { "PipingTemperature", "##PIPING_TEMPERATURE##CELSIUS" },
                { "PipingSlope", "##PIPING_SLOPE##PERCENTAGE" },
                { "PipingRoughness", "##PIPING_ROUGHNESS##MILLIMETERS" },
                { "PipingPressure", "##PIPING_PRESSURE##PASCALS" },
                { "PipingFriction", "##PIPING_FRICTION##PASCALS_PER_METER" },
                { "PipingFlow", "##PIPING_FLOW##LITERS_PER_SECOND" },
                { "PipingDensity", "##PIPING_DENSITY##KILOGRAMS_PER_CUBIC_METER" },
                { "PipeSize", "##PIPE_SIZE##MILLIMETERS" },
                { "PipeMassPerUnitLength", "##PIPE_MASS_PER_UNIT_LENGTH##KILOGRAMS_MASS_PER_METER" },
                { "PipeMass", "##PIPE_MASS##KILOGRAMS" },
                { "PipeInsulationThickness", "##NUMBER##GENERAL" },
                { "PipeDimension", "##PIPE_DIMENSION##MILLIMETERS" },
                { "Period", "##PERIOD##SECONDS" },
                { "NumberOfPoles", "##OTHER##" },
                { "Number", "##NUMBER##GENERAL" },
                { "MultilineText", "##OTHER##" },
                { "MomentOfInertia", "##MOMENT_OF_INERTIA##CENTIMETERS_TO_THE_FOURTH_POWER" },
                { "Moment", "##MOMENT##KILONEWTON_METERS" },
                { "Material", "##OTHER##" },
                { "MassPerUnitLength", "##MASS_PER_UNIT_LENGTH##KILOGRAMS_MASS_PER_METER" },
                { "MassPerUnitArea", "##MASS_PER_UNIT_AREA##POUNDS_MASS_PER_SQUARE_METER" },
                { "MassDensity", "##MASS_DENSITY##KILOGRAMS_PER_CUBIC_METER" },
                { "Mass", "##MASS##KILOGRAMS" },
                { "LoadClassification", "##OTHER##" },
                { "LinearMoment", "##LINEAR_MOMENT##KILONEWTON_METERS_PER_METER" },
                { "LinearForcePerLength", "##LINEAR_SPRING_COEFFICIENT##KILONEWTONS_PER_SQUARE_METER" },
                { "LinearForceLengthPerAngle", "##ROTATIONAL_LINEAR_SPRING_COEFFICIENT##KILONEWTON_METERS_PER_DEGREE_PER_METER" },
                { "LinearForce", "##LINEAR_FORCE##KILONEWTONS_PER_METER" },
                { "Length", "##LENGTH##MILLIMETERS" },
                { "Integer", "##NUMBER##GENERAL" },
                { "HVACViscosity", "##HVAC_VISCOSITY##PASCAL_SECONDS" },
                { "HVACVelocity", "##HVAC_VELOCITY##METERS_PER_SECOND" },
                { "HVACThermalResistance", "##HVAC_THERMAL_RESISTANCE##SQUARE_METER_KELVIN_PER_WATT" },
                { "HVACThermalMass", "##HVAC_THERMAL_MASS##KILOJOULES_PER_KELVIN" },
                { "HVACThermalConductivity", "##HVAC_THERMAL_CONDUCTIVITY##WATTS_PER_METER_KELVIN" },
                { "HVACTemperatureDifference", "##HVAC_TEMPERATURE_DIFFERENCE##CELSIUS_DIFFERENCE" },
                { "HVACTemperature", "##HVAC_TEMPERATURE##CELSIUS" },
                { "HVACSpecificHeatOfVaporization", "##HVAC_SPECIFIC_HEAT_OF_VAPORIZATION##JOULES_PER_GRAM" },
                { "HVACSpecificHeat", "##HVAC_SPECIFIC_HEAT##JOULES_PER_GRAM_CELSIUS" },
                { "HVACSlope", "##HVAC_SLOPE##PERCENTAGE" },
                { "HVACRoughness", "##HVAC_ROUGHNESS##MILLIMETERS" },
                { "HVACPressure", "##HVAC_PRESSURE##PASCALS" },
                { "HVACPowerDensity", "##HVAC_POWER_DENSITY##WATTS_PER_SQUARE_METER" },
                { "HVACPower", "##HVAC_POWER##WATTS" },
                { "HVACPermeability", "##HVAC_PERMEABILITY##NANOGRAMS_PER_PASCAL_SECOND_SQUARE_METER" },
                { "HVACHeatingLoadDividedByVolume", "##HVAC_HEATING_LOAD_DIVIDED_BY_VOLUME##WATTS_PER_CUBIC_METER" },
                { "HVACHeatingLoadDividedByArea", "##HVAC_HEATING_LOAD_DIVIDED_BY_AREA##WATTS_PER_SQUARE_METER" },
                { "HVACHeatingLoad", "##HVAC_HEATING_LOAD##WATTS" },
                { "HVACHeatGain", "##HVAC_HEAT_GAIN##WATTS" },
                { "HVACFriction", "##HVAC_FRICTION##PASCALS_PER_METER" },
                { "HVACFactor", "##HVAC_FACTOR##PERCENTAGE" },
                { "HVACEnergy", "##HVAC_ENERGY##JOULES" },
                { "HVACDuctSize", "##HVAC_DUCT_SIZE##MILLIMETERS" },
                { "HVACDuctLiningThickness", "##HVAC_DUCT_LINING_THICKNESS##MILLIMETERS" },
                { "HVACDuctInsulationThickness", "##NUMBER##GENERAL" },
                { "HVACDensity", "##HVAC_DENSITY##KILOGRAMS_PER_CUBIC_METER" },
                { "HVACCrossSection", "##HVAC_CROSS_SECTION##SQUARE_MILLIMETERS" },
                { "HVACCoolingLoadDividedByVolume", "##HVAC_COOLING_LOAD_DIVIDED_BY_VOLUME##WATTS_PER_CUBIC_METER" },
                { "HVACCoolingLoadDividedByArea", "##HVAC_COOLING_LOAD_DIVIDED_BY_AREA##WATTS_PER_SQUARE_METER" },
                { "HVACCoolingLoad", "##HVAC_COOLING_LOAD##WATTS" },
                { "HVACCoefficientOfHeatTransfer", "##HVAC_COEFFICIENT_OF_HEAT_TRANSFER##WATTS_PER_SQUARE_METER_KELVIN" },
                { "HVACAreaDividedByHeatingLoad", "##HVAC_AREA_DIVIDED_BY_HEATING_LOAD##CUBIC_SQUARE_METERS_PER_KILOWATTS" },
                { "HVACAreaDividedByCoolingLoad", "##HVAC_AREA_DIVIDED_BY_COOLING_LOAD##CUBIC_SQUARE_METERS_PER_KILOWATTS" },
                { "HVACAirflowDividedByVolume", "##HVAC_AIRFLOW_DIVIDED_BY_VOLUME##LITERS_PER_SECOND_CUBIC_METER" },
                { "HVACAirflowDividedByCoolingLoad", "##HVAC_AIRFLOW_DIVIDED_BY_COOLING_LOAD##LITERS_PER_SECOND_KILOWATTS" },
                { "HVACAirflowDensity", "##HVAC_AIRFLOW_DENSITY##LITERS_PER_SECOND_SQUARE_METER" },
                { "HVACAirflow", "##HVAC_AIR_FLOW##LITERS_PER_SECOND" },
                { "ForcePerLength", "##POINT_SPRING_COEFFICIENT##KILONEWTONS_PER_METER" },
                { "ForceLengthPerAngle", "##ROTATIONAL_POINT_SPRING_COEFFICIENT##KILONEWTON_METERS_PER_DEGREE" },
                { "Force", "##FORCE##KILONEWTONS" },
                { "FixtureUnit", "##OTHER##" },
                { "Energy", "##ENERGY##KILOJOULES" },
                { "ElectricalWattage", "##ELECTRICAL_WATTAGE##WATTS" },
                { "ElectricalTemperatureDifference", "##ELECTRICAL_TEMPERATURE_DIFFERENCE##CELSIUS_DIFFERENCE" },
                { "ElectricalTemperature", "##ELECTRICAL_TEMPERATURE##CELSIUS" },
                { "ElectricalResistivity", "##ELECTRICAL_RESISTIVITY##OHM_METERS" },
                { "ElectricalPowerDensity", "##ELECTRICAL_POWER_DENSITY##WATTS_PER_SQUARE_METER" },
                { "ElectricalPower", "##ELECTRICAL_POWER##WATTS" },
                { "ElectricalPotential", "##ELECTRICAL_POTENTIAL##VOLTS" },
                { "ElectricalLuminousIntensity", "##ELECTRICAL_LUMINOUS_INTENSITY##CANDELAS" },
                { "ElectricalLuminousFlux", "##ELECTRICAL_LUMINOUS_FLUX##LUMENS" },
                { "ElectricalLuminance", "##ELECTRICAL_LUMINANCE##CANDELAS_PER_SQUARE_METER" },
                { "ElectricalIlluminance", "##ELECTRICAL_ILLUMINANCE##LUX" },
                { "ElectricalFrequency", "##ELECTRICAL_FREQUENCY##HERTZ" },
                { "ElectricalEfficacy", "##ELECTRICAL_EFFICACY##LUMENS_PER_WATT" },
                { "ElectricalDemandFactor", "##ELECTRICAL_DEMAND_FACTOR##PERCENTAGE" },
                { "ElectricalCurrent", "##ELECTRICAL_CURRENT##AMPERES" },
                { "ElectricalConduitSize", "##CONDUIT_SIZE##MILLIMETERS" },
                { "ElectricalCableTraySize", "##CABLETRAY_SIZE##MILLIMETERS" },
                { "ElectricalApparentPower", "##ELECTRICAL_APPARENT_POWER##VOLT_AMPERES" },
                { "DisplacementDeflection", "##DISPLACEMENT/DEFLECTION##CENTIMETERS" },
                { "Currency", "##CURRENCY##CURRENCY" },
                { "CrackWidth", "##CRACK_WIDTH##MILLIMETERS" },
                { "ColorTemperature", "##COLOR_TEMPERATURE##KELVIN" },
                { "BarDiameter", "##BAR_DIAMETER##MILLIMETERS" },
                { "AreaForcePerLength", "##AREA_SPRING_COEFFICIENT##KILONEWTONS_PER_CUBIC_METER" },
                { "AreaForce", "##AREA_FORCE##KILONEWTONS_PER_SQUARE_METER" },
                { "Area", "##AREA##SQUARE_METERS" },
                { "Angle", "##ANGLE##DECIMAL DEGREES" },
                { "Acceleration", "##ACCELERATION##METERS_PER_SECOND_SQUARED" }


            };
            return dict;
        }
        public static Dictionary<string, string> GetDictionaryToConvertSizeTableColumnTypeInHeaderNameString2020()
        {
            Dictionary<string, string> dict = new Dictionary<string, string>()
            {
                {"UT_Undefined","##OTHER##"},
                {"UT_WireSize","##WIRE_SIZE##MILLIMETERS"},
                {"UT_Weight_per_Unit_Length","##WEIGHT_PER_UNIT_LENGTH##KILOGRAMS_FORCE_PER_METER"},
                {"UT_Weight","##WEIGHT##KILONEWTONS"},
                {"UT_Warping_Constant","##WARPING_CONSTANT##CENTIMETERS_TO_THE_SIXTH_POWER"},
                {"UT_Volume","##VOLUME##CUBIC_METERS"},
                {"UT_UnitWeight","##UNIT_WEIGHT##KILONEWTONS_PER_CUBIC_METER"},
                {"UT_TimeInterval","##TIMEINTERVAL##SECONDS"},
                {"UT_ThermalExpansion","##THERMAL_EXPANSION_COEFFICIENT##INVERSE_DEGREES_CELSIUS"},
                {"UT_Surface_Area","##SURFACE_AREA##SQUARE_METERS_PER_METER"},
                {"UT_Structural_Velocity","##VELOCITY##METERS_PER_SECOND"},
                {"UT_Structural_Frequency","##STRUCTURAL_FREQUENCY##HERTZ"},
                {"UT_Stress","##STRESS##MEGAPASCALS"},
                {"UT_Speed","##SPEED##KILOMETERS_PER_HOUR"},
                {"UT_Slope","##SLOPE##SLOPE_DEGREES"},
                {"UT_Section_Property","##SECTION_PROPERTY##CENTIMETERS"},
                {"UT_Section_Modulus","##SECTION_MODULUS##CUBIC_CENTIMETERS"},
                {"UT_Section_Dimension","##SECTION_DIMENSION##CENTIMETERS"},
                {"UT_Section_Area","##SECTION_AREA##SQUARE_CENTIMETERS"},
                {"UT_Rotation","##ROTATION##RADIANS"},
                {"UT_Reinforcement_Volume","##REINFORCEMENT_VOLUME##CUBIC_CENTIMETERS"},
                {"UT_Reinforcement_Spacing","##REINFORCEMENT_SPACING##MILLIMETERS"},
                {"UT_Reinforcement_Length","##REINFORCEMENT_LENGTH##MILLIMETERS"},
                {"UT_Reinforcement_Cover","##REINFORCEMENT_COVER##MILLIMETERS"},
                {"UT_Reinforcement_Area_per_Unit_Length","##REINFORCEMENT_AREA_PER_UNIT_LENGTH##SQUARE_CENTIMETERS_PER_METER"},
                {"UT_Reinforcement_Area","##REINFORCEMENT_AREA##SQUARE_CENTIMETERS"},
                {"UT_Pulsation","##PULSATION##RADIANS_PER_SECOND"},
                {"UT_Piping_Volume","##PIPING_VOLUME##LITERS"},
                {"UT_Piping_Viscosity","##PIPING_VISCOSITY##PASCAL_SECONDS"},
                {"UT_Piping_Velocity","##PIPING_VELOCITY##METERS_PER_SECOND"},
                {"UT_Piping_TemperatureDifference","##PIPING_TEMPERATURE_DIFFERENCE##CELSIUS_DIFFERENCE"},
                {"UT_Piping_Temperature","##PIPING_TEMPERATURE##CELSIUS"},
                {"UT_Piping_Slope","##PIPING_SLOPE##PERCENTAGE"},
                {"UT_Piping_Roughness","##PIPING_ROUGHNESS##MILLIMETERS"},
                {"UT_Piping_Pressure","##PIPING_PRESSURE##PASCALS"},
                {"UT_Piping_Friction","##PIPING_FRICTION##PASCALS_PER_METER"},
                {"UT_Piping_Flow","##PIPING_FLOW##LITERS_PER_SECOND"},
                {"UT_Piping_Density","##PIPING_DENSITY##KILOGRAMS_PER_CUBIC_METER"},
                {"UT_PipeSize","##PIPE_SIZE##MILLIMETERS"},
                {"UT_PipeMassPerUnitLength","##PIPE_MASS_PER_UNIT_LENGTH##KILOGRAMS_MASS_PER_METER"},
                {"UT_PipeMass","##PIPE_MASS##KILOGRAMS"},
                {"UT_Number","##NUMBER##GENERAL"},
                {"UT_Pipe_Dimension","##PIPE_DIMENSION##MILLIMETERS"},
                {"UT_Period","##PERIOD##SECONDS"},
                {"UT_Moment_of_Inertia","##MOMENT_OF_INERTIA##CENTIMETERS_TO_THE_FOURTH_POWER"},
                {"UT_Moment","##MOMENT##KILONEWTON_METERS"},
                {"UT_Mass_per_Unit_Length","##MASS_PER_UNIT_LENGTH##KILOGRAMS_MASS_PER_METER"},
                {"UT_MassPerUnitArea","##MASS_PER_UNIT_AREA##POUNDS_MASS_PER_SQUARE_METER"},
                {"UT_MassDensity","##MASS_DENSITY##KILOGRAMS_PER_CUBIC_METER"},
                {"UT_Mass","##MASS##KILOGRAMS"},
                {"UT_LinearMoment","##LINEAR_MOMENT##KILONEWTON_METERS_PER_METER"},
                {"UT_LinearForcePerLength","##LINEAR_SPRING_COEFFICIENT##KILONEWTONS_PER_SQUARE_METER"},
                {"UT_LinearForceLengthPerAngle","##ROTATIONAL_LINEAR_SPRING_COEFFICIENT##KILONEWTON_METERS_PER_DEGREE_PER_METER"},
                {"UT_LinearForce","##LINEAR_FORCE##KILONEWTONS_PER_METER"},
                {"UT_Length","##LENGTH##MILLIMETERS"},
                {"UT_HVAC_Viscosity","##HVAC_VISCOSITY##PASCAL_SECONDS"},
                {"UT_HVAC_Velocity","##HVAC_VELOCITY##METERS_PER_SECOND"},
                {"UT_HVAC_ThermalResistance","##HVAC_THERMAL_RESISTANCE##SQUARE_METER_KELVIN_PER_WATT"},
                {"UT_HVAC_ThermalMass","##HVAC_THERMAL_MASS##KILOJOULES_PER_KELVIN"},
                {"UT_HVAC_ThermalConductivity","##HVAC_THERMAL_CONDUCTIVITY##WATTS_PER_METER_KELVIN"},
                {"UT_HVAC_TemperatureDifference","##HVAC_TEMPERATURE_DIFFERENCE##CELSIUS_DIFFERENCE"},
                {"UT_HVAC_Temperature","##HVAC_TEMPERATURE##CELSIUS"},
                {"UT_HVAC_SpecificHeatOfVaporization","##HVAC_SPECIFIC_HEAT_OF_VAPORIZATION##JOULES_PER_GRAM"},
                {"UT_HVAC_SpecificHeat","##HVAC_SPECIFIC_HEAT##JOULES_PER_GRAM_CELSIUS"},
                {"UT_HVAC_Slope","##HVAC_SLOPE##PERCENTAGE"},
                {"UT_HVAC_Roughness","##HVAC_ROUGHNESS##MILLIMETERS"},
                {"UT_HVAC_Pressure","##HVAC_PRESSURE##PASCALS"},
                {"UT_HVAC_Power_Density","##HVAC_POWER_DENSITY##WATTS_PER_SQUARE_METER"},
                {"UT_HVAC_Power","##HVAC_POWER##WATTS"},
                {"UT_HVAC_Permeability","##HVAC_PERMEABILITY##NANOGRAMS_PER_PASCAL_SECOND_SQUARE_METER"},
                {"UT_HVAC_Heating_Load_Divided_By_Volume","##HVAC_HEATING_LOAD_DIVIDED_BY_VOLUME##WATTS_PER_CUBIC_METER"},
                {"UT_HVAC_Heating_Load_Divided_By_Area","##HVAC_HEATING_LOAD_DIVIDED_BY_AREA##WATTS_PER_SQUARE_METER"},
                {"UT_HVAC_Heating_Load","##HVAC_HEATING_LOAD##WATTS"},
                {"UT_HVAC_HeatGain","##HVAC_HEAT_GAIN##WATTS"},
                {"UT_HVAC_Friction","##HVAC_FRICTION##PASCALS_PER_METER"},
                {"UT_HVAC_Factor","##HVAC_FACTOR##PERCENTAGE"},
                {"UT_HVAC_Energy","##HVAC_ENERGY##JOULES"},
                {"UT_HVAC_DuctSize","##HVAC_DUCT_SIZE##MILLIMETERS"},
                {"UT_HVAC_DuctLiningThickness","##HVAC_DUCT_LINING_THICKNESS##MILLIMETERS"},
                {"UT_HVAC_DuctInsulationThickness","##HVAC_DUCT_INSULATION_THICKNESS##MILLIMETERS"},
                {"UT_HVAC_Density","##HVAC_DENSITY##KILOGRAMS_PER_CUBIC_METER"},
                {"UT_HVAC_CrossSection","##HVAC_CROSS_SECTION##SQUARE_MILLIMETERS"},
                {"UT_HVAC_Cooling_Load_Divided_By_Volume","##HVAC_COOLING_LOAD_DIVIDED_BY_VOLUME##WATTS_PER_CUBIC_METER"},
                {"UT_HVAC_Cooling_Load_Divided_By_Area","##HVAC_COOLING_LOAD_DIVIDED_BY_AREA##WATTS_PER_SQUARE_METER"},
                {"UT_HVAC_Cooling_Load","##HVAC_COOLING_LOAD##WATTS"},
                {"UT_HVAC_CoefficientOfHeatTransfer","##HVAC_COEFFICIENT_OF_HEAT_TRANSFER##WATTS_PER_SQUARE_METER_KELVIN"},
                {"UT_HVAC_Area_Divided_By_Heating_Load","##HVAC_AREA_DIVIDED_BY_HEATING_LOAD##CUBIC_SQUARE_METERS_PER_KILOWATTS"},
                {"UT_HVAC_Area_Divided_By_Cooling_Load","##HVAC_AREA_DIVIDED_BY_COOLING_LOAD##CUBIC_SQUARE_METERS_PER_KILOWATTS"},
                {"UT_HVAC_Airflow_Divided_By_Volume","##HVAC_AIRFLOW_DIVIDED_BY_VOLUME##LITERS_PER_SECOND_CUBIC_METER"},
                {"UT_HVAC_Airflow_Divided_By_Cooling_Load","##HVAC_AIRFLOW_DIVIDED_BY_COOLING_LOAD##LITERS_PER_SECOND_KILOWATTS"},
                {"UT_HVAC_Airflow_Density","##HVAC_AIRFLOW_DENSITY##LITERS_PER_SECOND_SQUARE_METER"},
                {"UT_HVAC_Airflow","##HVAC_AIR_FLOW##LITERS_PER_SECOND"},
                {"UT_ForcePerLength","##POINT_SPRING_COEFFICIENT##KILONEWTONS_PER_METER"},
                {"UT_ForceLengthPerAngle","##ROTATIONAL_POINT_SPRING_COEFFICIENT##KILONEWTON_METERS_PER_DEGREE"},
                {"UT_Force","##FORCE##KILONEWTONS"},
                {"UT_Energy","##ENERGY##KILOJOULES"},
                {"UT_Electrical_Wattage","##ELECTRICAL_WATTAGE##WATTS"},
                {"UT_Electrical_TemperatureDifference","##ELECTRICAL_TEMPERATURE_DIFFERENCE##CELSIUS_DIFFERENCE"},
                {"UT_Electrical_Temperature","##ELECTRICAL_TEMPERATURE##CELSIUS"},
                {"UT_Electrical_Resistivity","##ELECTRICAL_RESISTIVITY##OHM_METERS"},
                {"UT_Electrical_Power_Density","##ELECTRICAL_POWER_DENSITY##WATTS_PER_SQUARE_METER"},
                {"UT_Electrical_Power","##ELECTRICAL_POWER##WATTS"},
                {"UT_Electrical_Potential","##ELECTRICAL_POTENTIAL##VOLTS"},
                {"UT_Electrical_Luminous_Intensity","##ELECTRICAL_LUMINOUS_INTENSITY##CANDELAS"},
                {"UT_Electrical_Luminous_Flux","##ELECTRICAL_LUMINOUS_FLUX##LUMENS"},
                {"UT_Electrical_Luminance","##ELECTRICAL_LUMINANCE##CANDELAS_PER_SQUARE_METER"},
                {"UT_Electrical_Illuminance","##ELECTRICAL_ILLUMINANCE##LUX"},
                {"UT_Electrical_Frequency","##ELECTRICAL_FREQUENCY##HERTZ"},
                {"UT_Electrical_Efficacy","##ELECTRICAL_EFFICACY##LUMENS_PER_WATT"},
                {"UT_Electrical_Demand_Factor","##ELECTRICAL_DEMAND_FACTOR##PERCENTAGE"},
                {"UT_Electrical_Current","##ELECTRICAL_CURRENT##AMPERES"},
                {"UT_Electrical_ConduitSize","##CONDUIT_SIZE##MILLIMETERS"},
                {"UT_Electrical_CableTraySize","##CABLETRAY_SIZE##MILLIMETERS"},
                {"UT_Electrical_Apparent_Power","##ELECTRICAL_APPARENT_POWER##VOLT_AMPERES"},
                {"UT_Displacement_Deflection","##DISPLACEMENT/DEFLECTION##CENTIMETERS"},
                {"UT_Currency","##CURRENCY##CURRENCY"},
                {"UT_Crack_Width","##CRACK_WIDTH##MILLIMETERS"},
                {"UT_Color_Temperature","##COLOR_TEMPERATURE##KELVIN"},
                {"UT_Bar_Diameter","##BAR_DIAMETER##MILLIMETERS"},
                {"UT_AreaForcePerLength","##AREA_SPRING_COEFFICIENT##KILONEWTONS_PER_CUBIC_METER"},
                {"UT_AreaForce","##AREA_FORCE##KILONEWTONS_PER_SQUARE_METER"},
                {"UT_Area","##AREA##SQUARE_METERS"},
                {"UT_Angle","##ANGLE##DECIMAL DEGREES"},
                {"UT_Acceleration","##ACCELERATION##METERS_PER_SECOND_SQUARED"}

            };
            return dict;
        }
        public static Dictionary<string, string> GetDictionaryToConvertParamTypeInSizeTableHeaderString2021()
        {
            Dictionary<string, string> dict = new Dictionary<string, string>
            {
                {"YesNo","##NUMBER##GENERAL"},
                {"WireSize","##WIRE_SIZE##MILLIMETERS"},
                {"WeightPerUnitLength","##WEIGHT_PER_UNIT_LENGTH##KILOGRAMS_FORCE_PER_METER"},
                {"Weight","##WEIGHT##KILONEWTONS"},
                {"WarpingConstant","##WARPING_CONSTANT##CENTIMETERS_TO_THE_SIXTH_POWER"},
                {"Volume","##VOLUME##CUBIC_METERS"},
                {"UnitWeight","##UNIT_WEIGHT##KILONEWTONS_PER_CUBIC_METER"},
                {"TimeInterval","##TIMEINTERVAL##SECONDS"},
                {"ThermalExpansion","##THERMAL_EXPANSION_COEFFICIENT##INVERSE_DEGREES_CELSIUS"},
                {"Text","##OTHER##"},
                {"SurfaceArea","##SURFACE_AREA##SQUARE_METERS_PER_METER"},
                {"StructuralVelocity","##VELOCITY##METERS_PER_SECOND"},
                {"StructuralFrequency","##STRUCTURAL_FREQUENCY##HERTZ"},
                {"Stress","##STRESS##MEGAPASCALS"},
                {"Speed","##SPEED##KILOMETERS_PER_HOUR"},
                {"Slope","##SLOPE##SLOPE_DEGREES"},
                {"SectionProperty","##SECTION_PROPERTY##CENTIMETERS"},
                {"SectionModulus","##SECTION_MODULUS##CUBIC_CENTIMETERS"},
                {"SectionDimension","##SECTION_DIMENSION##CENTIMETERS"},
                {"SectionArea","##SECTION_AREA##SQUARE_CENTIMETERS"},
                {"Rotation","##ROTATION##RADIANS"},
                {"ReinforcementVolume","##REINFORCEMENT_VOLUME##CUBIC_CENTIMETERS"},
                {"ReinforcementSpacing","##REINFORCEMENT_SPACING##MILLIMETERS"},
                {"ReinforcementLength","##REINFORCEMENT_LENGTH##MILLIMETERS"},
                {"ReinforcementCover","##REINFORCEMENT_COVER##MILLIMETERS"},
                {"ReinforcementAreaPerUnitLength","##REINFORCEMENT_AREA_PER_UNIT_LENGTH##SQUARE_CENTIMETERS_PER_METER"},
                {"ReinforcementArea","##REINFORCEMENT_AREA##SQUARE_CENTIMETERS"},
                {"Pulsation","##PULSATION##RADIANS_PER_SECOND"},
                {"PipingVolume","##PIPING_VOLUME##LITERS"},
                {"PipingViscosity","##PIPING_VISCOSITY##PASCAL_SECONDS"},
                {"PipingVelocity","##PIPING_VELOCITY##METERS_PER_SECOND"},
                {"PipingTemperatureDifference","##PIPING_TEMPERATURE_DIFFERENCE##CELSIUS_INTERVAL"},
                {"PipingTemperature","##PIPING_TEMPERATURE##CELSIUS"},
                {"PipingSlope","##PIPING_SLOPE##PERCENTAGE"},
                {"PipingRoughness","##PIPING_ROUGHNESS##MILLIMETERS"},
                {"PipingPressure","##PIPING_PRESSURE##PASCALS"},
                {"PipingFriction","##PIPING_FRICTION##PASCALS_PER_METER"},
                {"PipingFlow","##PIPING_FLOW##LITERS_PER_SECOND"},
                {"PipingDensity","##PIPING_DENSITY##KILOGRAMS_PER_CUBIC_METER"},
                {"PipeSize","##PIPE_SIZE##MILLIMETERS"},
                {"PipeMassPerUnitLength","##PIPE_MASS_PER_UNIT_LENGTH##KILOGRAMS_PER_METER"},
                {"PipeMass","##PIPE_MASS##KILOGRAMS"},
                {"PipeInsulationThickness","##NUMBER##GENERAL"},
                {"PipeDimension","##PIPE_DIMENSION##MILLIMETERS"},
                {"Period","##PERIOD##SECONDS"},
                {"NumberOfPoles","##NUMBER##GENERAL"},
                {"Number","##NUMBER##GENERAL"},
                {"MultilineText","##OTHER##"},
                {"MomentOfInertia","##MOMENT_OF_INERTIA##CENTIMETERS_TO_THE_FOURTH_POWER"},
                {"Moment","##MOMENT##KILONEWTON_METERS"},
                {"Material","##OTHER##"},
                {"MassPerUnitLength","##MASS_PER_UNIT_LENGTH##KILOGRAMS_PER_METER"},
                {"MassPerUnitArea","##MASS_PER_UNIT_AREA##KILOGRAMS_PER_SQUARE_METER"},
                {"MassDensity","##MASS_DENSITY##KILOGRAMS_PER_CUBIC_METER"},
                {"Mass","##MASS##KILOGRAMS"},
                {"LoadClassification","##OTHER##"},
                {"LinearMoment","##LINEAR_MOMENT##KILONEWTON_METERS_PER_METER"},
                {"LinearForcePerLength","##LINEAR_SPRING_COEFFICIENT##KILONEWTONS_PER_SQUARE_METER"},
                {"LinearForceLengthPerAngle","##ROTATIONAL_LINEAR_SPRING_COEFFICIENT##KILONEWTON_METERS_PER_DEGREE_PER_METER"},
                {"LinearForce","##LINEAR_FORCE##KILONEWTONS_PER_METER"},
                {"Length","##LENGTH##MILLIMETERS"},
                {"Integer","##NUMBER##GENERAL"},
                {"HVACViscosity","##HVAC_VISCOSITY##PASCAL_SECONDS"},
                {"HVACVelocity","##HVAC_VELOCITY##METERS_PER_SECOND"},
                {"HVACThermalResistance","##HVAC_THERMAL_RESISTANCE##SQUARE_METER_KELVINS_PER_WATT"},
                {"HVACThermalMass","##HVAC_THERMAL_MASS##KILOJOULES_PER_KELVIN"},
                {"HVACThermalConductivity","##HVAC_THERMAL_CONDUCTIVITY##WATTS_PER_METER_KELVIN"},
                {"HVACTemperatureDifference","##HVAC_TEMPERATURE_DIFFERENCE##CELSIUS_INTERVAL"},
                {"HVACTemperature","##HVAC_TEMPERATURE##CELSIUS"},
                {"HVACSpecificHeatOfVaporization","##HVAC_SPECIFIC_HEAT_OF_VAPORIZATION##JOULES_PER_GRAM"},
                {"HVACSpecificHeat","##HVAC_SPECIFIC_HEAT##JOULES_PER_GRAM_DEGREE_CELSIUS"},
                {"HVACSlope","##HVAC_SLOPE##PERCENTAGE"},
                {"HVACRoughness","##HVAC_ROUGHNESS##MILLIMETERS"},
                {"HVACPressure","##HVAC_PRESSURE##PASCALS"},
                {"HVACPowerDensity","##HVAC_POWER_DENSITY##WATTS_PER_SQUARE_METER"},
                {"HVACPower","##HVAC_POWER##WATTS"},
                {"HVACPermeability","##HVAC_PERMEABILITY##NANOGRAMS_PER_PASCAL_SECOND_SQUARE_METER"},
                {"HVACHeatingLoadDividedByVolume","##HVAC_HEATING_LOAD_DIVIDED_BY_VOLUME##WATTS_PER_CUBIC_METER"},
                {"HVACHeatingLoadDividedByArea","##HVAC_HEATING_LOAD_DIVIDED_BY_AREA##WATTS_PER_SQUARE_METER"},
                {"HVACHeatingLoad","##HVAC_HEATING_LOAD##WATTS"},
                {"HVACHeatGain","##HVAC_HEAT_GAIN##WATTS"},
                {"HVACFriction","##HVAC_FRICTION##PASCALS_PER_METER"},
                {"HVACFactor","##HVAC_FACTOR##PERCENTAGE"},
                {"HVACEnergy","##HVAC_ENERGY##JOULES"},
                {"HVACDuctSize","##HVAC_DUCT_SIZE##MILLIMETERS"},
                {"HVACDuctLiningThickness","##HVAC_DUCT_LINING_THICKNESS##MILLIMETERS"},
                {"HVACDuctInsulationThickness","##HVAC_DUCT_INSULATION_THICKNESS##MILLIMETERS"},
                {"HVACDensity","##HVAC_DENSITY##KILOGRAMS_PER_CUBIC_METER"},
                {"HVACCrossSection","##HVAC_CROSS_SECTION##SQUARE_MILLIMETERS"},
                {"HVACCoolingLoadDividedByVolume","##HVAC_COOLING_LOAD_DIVIDED_BY_VOLUME##WATTS_PER_CUBIC_METER"},
                {"HVACCoolingLoadDividedByArea","##HVAC_COOLING_LOAD_DIVIDED_BY_AREA##WATTS_PER_SQUARE_METER"},
                {"HVACCoolingLoad","##HVAC_COOLING_LOAD##WATTS"},
                {"HVACCoefficientOfHeatTransfer","##HVAC_COEFFICIENT_OF_HEAT_TRANSFER##WATTS_PER_SQUARE_METER_KELVIN"},
                {"HVACAreaDividedByHeatingLoad","##HVAC_AREA_DIVIDED_BY_HEATING_LOAD##SQUARE_METERS_PER_KILOWATT"},
                {"HVACAreaDividedByCoolingLoad","##HVAC_AREA_DIVIDED_BY_COOLING_LOAD##SQUARE_METERS_PER_KILOWATT"},
                {"HVACAirflowDividedByVolume","##HVAC_AIRFLOW_DIVIDED_BY_VOLUME##LITERS_PER_SECOND_CUBIC_METER"},
                {"HVACAirflowDividedByCoolingLoad","##HVAC_AIRFLOW_DIVIDED_BY_COOLING_LOAD##LITERS_PER_SECOND_KILOWATT"},
                {"HVACAirflowDensity","##HVAC_AIRFLOW_DENSITY##LITERS_PER_SECOND_SQUARE_METER"},
                {"HVACAirflow","##HVAC_AIR_FLOW##LITERS_PER_SECOND"},
                {"ForcePerLength","##POINT_SPRING_COEFFICIENT##KILONEWTONS_PER_METER"},
                {"ForceLengthPerAngle","##ROTATIONAL_POINT_SPRING_COEFFICIENT##KILONEWTON_METERS_PER_DEGREE"},
                {"Force","##FORCE##KILONEWTONS"},
                {"FixtureUnit","##NUMBER##GENERAL"},
                {"Energy","##ENERGY##KILOJOULES"},
                {"ElectricalWattage","##ELECTRICAL_WATTAGE##WATTS"},
                {"ElectricalTemperatureDifference","##ELECTRICAL_TEMPERATURE_DIFFERENCE##CELSIUS_INTERVAL"},
                {"ElectricalTemperature","##ELECTRICAL_TEMPERATURE##CELSIUS"},
                {"ElectricalResistivity","##ELECTRICAL_RESISTIVITY##OHM_METERS"},
                {"ElectricalPowerDensity","##ELECTRICAL_POWER_DENSITY##WATTS_PER_SQUARE_METER"},
                {"ElectricalPower","##ELECTRICAL_POWER##WATTS"},
                {"ElectricalPotential","##ELECTRICAL_POTENTIAL##VOLTS"},
                {"ElectricalLuminousIntensity","##ELECTRICAL_LUMINOUS_INTENSITY##CANDELAS"},
                {"ElectricalLuminousFlux","##ELECTRICAL_LUMINOUS_FLUX##LUMENS"},
                {"ElectricalLuminance","##ELECTRICAL_LUMINANCE##CANDELAS_PER_SQUARE_METER"},
                {"ElectricalIlluminance","##ELECTRICAL_ILLUMINANCE##LUX"},
                {"ElectricalFrequency","##ELECTRICAL_FREQUENCY##HERTZ"},
                {"ElectricalEfficacy","##ELECTRICAL_EFFICACY##LUMENS_PER_WATT"},
                {"ElectricalDemandFactor","##ELECTRICAL_DEMAND_FACTOR##PERCENTAGE"},
                {"ElectricalCurrent","##ELECTRICAL_CURRENT##AMPERES"},
                {"ElectricalConduitSize","##CONDUIT_SIZE##MILLIMETERS"},
                {"ElectricalCableTraySize","##CABLETRAY_SIZE##MILLIMETERS"},
                {"ElectricalApparentPower","##ELECTRICAL_APPARENT_POWER##VOLT_AMPERES"},
                {"DisplacementDeflection","##DISPLACEMENT/DEFLECTION##CENTIMETERS"},
                {"Currency","##CURRENCY##CURRENCY"},
                {"CrackWidth","##CRACK_WIDTH##MILLIMETERS"},
                {"ColorTemperature","##COLOR_TEMPERATURE##KELVIN"},
                {"BarDiameter","##BAR_DIAMETER##MILLIMETERS"},
                {"AreaForcePerLength","##AREA_SPRING_COEFFICIENT##KILONEWTONS_PER_CUBIC_METER"},
                {"AreaForce","##AREA_FORCE##KILONEWTONS_PER_SQUARE_METER"},
                {"Area","##AREA##SQUARE_METERS"},
                {"Angle","##ANGLE##DEGREES"},
                {"Acceleration","##ACCELERATION##METERS_PER_SECOND_SQUARED"}
            };
            return dict;
        }
        public static Dictionary<string, string> GetDictionaryToConvertSizeTableColumnTypeInHeaderNameString2021()
        {
            Dictionary<string, string> dict = new Dictionary<string, string>()
            {
                { "UT_Acceleration", "##ACCELERATION##METERS_PER_SECOND_SQUARED" },
                { "UT_Angle", "##ANGLE##DEGREES" },
                { "UT_Area", "##AREA##SQUARE_METERS" },
                { "UT_AreaForce", "##AREA_FORCE##KILONEWTONS_PER_SQUARE_METER" },
                { "UT_AreaForcePerLength", "##AREA_SPRING_COEFFICIENT##KILONEWTONS_PER_CUBIC_METER" },
                { "UT_Bar_Diameter", "##BAR_DIAMETER##MILLIMETERS" },
                { "UT_Color_Temperature", "##COLOR_TEMPERATURE##KELVIN" },
                { "UT_Crack_Width", "##CRACK_WIDTH##MILLIMETERS" },
                { "UT_Currency", "##CURRENCY##CURRENCY" },
                { "UT_Displacement_Deflection", "##DISPLACEMENT/DEFLECTION##CENTIMETERS" },
                { "UT_Electrical_Apparent_Power", "##ELECTRICAL_APPARENT_POWER##VOLT_AMPERES" },
                { "UT_Electrical_CableTraySize", "##CABLETRAY_SIZE##MILLIMETERS" },
                { "UT_Electrical_ConduitSize", "##CONDUIT_SIZE##MILLIMETERS" },
                { "UT_Electrical_Current", "##ELECTRICAL_CURRENT##AMPERES" },
                { "UT_Electrical_Demand_Factor", "##ELECTRICAL_DEMAND_FACTOR##PERCENTAGE" },
                { "UT_Electrical_Efficacy", "##ELECTRICAL_EFFICACY##LUMENS_PER_WATT" },
                { "UT_Electrical_Frequency", "##ELECTRICAL_FREQUENCY##HERTZ" },
                {"UT_Electrical_Illuminance","##ELECTRICAL_ILLUMINANCE##LUX"},
                {"UT_Electrical_Luminance","##ELECTRICAL_LUMINANCE##CANDELAS_PER_SQUARE_METER"},
                {"UT_Electrical_Luminous_Flux","##ELECTRICAL_LUMINOUS_FLUX##LUMENS"},
                {"UT_Electrical_Luminous_Intensity","##ELECTRICAL_LUMINOUS_INTENSITY##CANDELAS"},
                {"UT_Electrical_Potential","##ELECTRICAL_POTENTIAL##VOLTS"},
                {"UT_Electrical_Power","##ELECTRICAL_POWER##WATTS"},
                {"UT_Electrical_Power_Density","##ELECTRICAL_POWER_DENSITY##WATTS_PER_SQUARE_METER"},
                {"UT_Electrical_Resistivity","##ELECTRICAL_RESISTIVITY##OHM_METERS"},
                {"UT_Electrical_Temperature","##ELECTRICAL_TEMPERATURE##CELSIUS"},
                {"UT_Electrical_TemperatureDifference","##ELECTRICAL_TEMPERATURE_DIFFERENCE##CELSIUS_INTERVAL"},
                {"UT_Electrical_Wattage","##ELECTRICAL_WATTAGE##WATTS"},
                {"UT_Energy","##ENERGY##KILOJOULES"},
                {"UT_Number","##OTHER##"},
                {"UT_Force","##FORCE##KILONEWTONS"},
                {"UT_ForceLengthPerAngle","##ROTATIONAL_POINT_SPRING_COEFFICIENT##KILONEWTON_METERS_PER_DEGREE"},
                {"UT_ForcePerLength","##POINT_SPRING_COEFFICIENT##KILONEWTONS_PER_METER"},
                {"UT_HVAC_Airflow","##HVAC_AIR_FLOW##LITERS_PER_SECOND"},
                {"UT_HVAC_Airflow_Density","##HVAC_AIRFLOW_DENSITY##LITERS_PER_SECOND_SQUARE_METER"},
                {"UT_HVAC_Airflow_Divided_By_Cooling_Load","##HVAC_AIRFLOW_DIVIDED_BY_COOLING_LOAD##LITERS_PER_SECOND_KILOWATT"},
                {"UT_HVAC_Airflow_Divided_By_Volume","##HVAC_AIRFLOW_DIVIDED_BY_VOLUME##LITERS_PER_SECOND_CUBIC_METER"},
                {"UT_HVAC_Area_Divided_By_Cooling_Load","##HVAC_AREA_DIVIDED_BY_COOLING_LOAD##SQUARE_METERS_PER_KILOWATT"},
                {"UT_HVAC_Area_Divided_By_Heating_Load","##HVAC_AREA_DIVIDED_BY_HEATING_LOAD##SQUARE_METERS_PER_KILOWATT"},
                {"UT_HVAC_CoefficientOfHeatTransfer","##HVAC_COEFFICIENT_OF_HEAT_TRANSFER##WATTS_PER_SQUARE_METER_KELVIN"},
                {"UT_HVAC_Cooling_Load","##HVAC_COOLING_LOAD##WATTS"},
                {"UT_HVAC_Cooling_Load_Divided_By_Area","##HVAC_COOLING_LOAD_DIVIDED_BY_AREA##WATTS_PER_SQUARE_METER"},
                {"UT_HVAC_Cooling_Load_Divided_By_Volume","##HVAC_COOLING_LOAD_DIVIDED_BY_VOLUME##WATTS_PER_CUBIC_METER"},
                {"UT_HVAC_CrossSection","##HVAC_CROSS_SECTION##SQUARE_MILLIMETERS"},
                {"UT_HVAC_Density","##HVAC_DENSITY##KILOGRAMS_PER_CUBIC_METER"},
                {"UT_HVAC_DuctInsulationThickness","##HVAC_DUCT_INSULATION_THICKNESS##MILLIMETERS"},
                {"UT_HVAC_DuctLiningThickness","##HVAC_DUCT_LINING_THICKNESS##MILLIMETERS"},
                {"UT_HVAC_DuctSize","##HVAC_DUCT_SIZE##MILLIMETERS"},
                {"UT_HVAC_Energy","##HVAC_ENERGY##JOULES"},
                {"UT_HVAC_Factor","##HVAC_FACTOR##PERCENTAGE"},
                {"UT_HVAC_Friction","##HVAC_FRICTION##PASCALS_PER_METER"},
                {"UT_HVAC_HeatGain","##HVAC_HEAT_GAIN##WATTS"},
                {"UT_HVAC_Heating_Load","##HVAC_HEATING_LOAD##WATTS"},
                {"UT_HVAC_Heating_Load_Divided_By_Area","##HVAC_HEATING_LOAD_DIVIDED_BY_AREA##WATTS_PER_SQUARE_METER"},
                {"UT_HVAC_Heating_Load_Divided_By_Volume","##HVAC_HEATING_LOAD_DIVIDED_BY_VOLUME##WATTS_PER_CUBIC_METER"},
                {"UT_HVAC_Permeability","##HVAC_PERMEABILITY##NANOGRAMS_PER_PASCAL_SECOND_SQUARE_METER"},
                {"UT_HVAC_Power","##HVAC_POWER##WATTS"},
                {"UT_HVAC_Power_Density","##HVAC_POWER_DENSITY##WATTS_PER_SQUARE_METER"},
                {"UT_HVAC_Pressure","##HVAC_PRESSURE##PASCALS"},
                {"UT_HVAC_Roughness","##HVAC_ROUGHNESS##MILLIMETERS"},
                {"UT_HVAC_Slope","##HVAC_SLOPE##PERCENTAGE"},
                {"UT_HVAC_SpecificHeat","##HVAC_SPECIFIC_HEAT##JOULES_PER_GRAM_DEGREE_CELSIUS"},
                {"UT_HVAC_SpecificHeatOfVaporization","##HVAC_SPECIFIC_HEAT_OF_VAPORIZATION##JOULES_PER_GRAM"},
                {"UT_HVAC_Temperature","##HVAC_TEMPERATURE##CELSIUS"},
                {"UT_HVAC_TemperatureDifference","##HVAC_TEMPERATURE_DIFFERENCE##CELSIUS_INTERVAL"},
                {"UT_HVAC_ThermalConductivity","##HVAC_THERMAL_CONDUCTIVITY##WATTS_PER_METER_KELVIN"},
                {"UT_HVAC_ThermalMass","##HVAC_THERMAL_MASS##KILOJOULES_PER_KELVIN"},
                {"UT_HVAC_ThermalResistance","##HVAC_THERMAL_RESISTANCE##SQUARE_METER_KELVINS_PER_WATT"},
                {"UT_HVAC_Velocity","##HVAC_VELOCITY##METERS_PER_SECOND"},
                {"UT_HVAC_Viscosity","##HVAC_VISCOSITY##PASCAL_SECONDS"},
                {"UT_Length","##LENGTH##MILLIMETERS"},
                {"UT_LinearForce","##LINEAR_FORCE##KILONEWTONS_PER_METER"},
                {"UT_LinearForceLengthPerAngle","##ROTATIONAL_LINEAR_SPRING_COEFFICIENT##KILONEWTON_METERS_PER_DEGREE_PER_METER"},
                {"UT_LinearForcePerLength","##LINEAR_SPRING_COEFFICIENT##KILONEWTONS_PER_SQUARE_METER"},
                {"UT_LinearMoment","##LINEAR_MOMENT##KILONEWTON_METERS_PER_METER"},
                {"UT_Undefined","##OTHER##"},
                {"UT_Mass","##MASS##KILOGRAMS"},
                {"UT_MassDensity","##MASS_DENSITY##KILOGRAMS_PER_CUBIC_METER"},
                {"UT_MassPerUnitArea","##MASS_PER_UNIT_AREA##KILOGRAMS_PER_SQUARE_METER"},
                {"UT_Mass_per_Unit_Length","##MASS_PER_UNIT_LENGTH##KILOGRAMS_PER_METER"},
                {"UT_Moment","##MOMENT##KILONEWTON_METERS"},
                {"UT_Moment_of_Inertia","##MOMENT_OF_INERTIA##CENTIMETERS_TO_THE_FOURTH_POWER"},
                {"UT_Period","##PERIOD##SECONDS"},
                {"UT_Pipe_Dimension","##PIPE_DIMENSION##MILLIMETERS"},
                {"UT_PipeMass","##PIPE_MASS##KILOGRAMS"},
                {"UT_PipeMassPerUnitLength","##PIPE_MASS_PER_UNIT_LENGTH##KILOGRAMS_PER_METER"},
                {"UT_PipeSize","##PIPE_SIZE##MILLIMETERS"},
                {"UT_Piping_Density","##PIPING_DENSITY##KILOGRAMS_PER_CUBIC_METER"},
                {"UT_Piping_Flow","##PIPING_FLOW##LITERS_PER_SECOND"},
                {"UT_Piping_Friction","##PIPING_FRICTION##PASCALS_PER_METER"},
                {"UT_Piping_Pressure","##PIPING_PRESSURE##PASCALS"},
                {"UT_Piping_Roughness","##PIPING_ROUGHNESS##MILLIMETERS"},
                {"UT_Piping_Slope","##PIPING_SLOPE##PERCENTAGE"},
                {"UT_Piping_Temperature","##PIPING_TEMPERATURE##CELSIUS"},
                {"UT_Piping_TemperatureDifference","##PIPING_TEMPERATURE_DIFFERENCE##CELSIUS_INTERVAL"},
                {"UT_Piping_Velocity","##PIPING_VELOCITY##METERS_PER_SECOND"},
                {"UT_Piping_Viscosity","##PIPING_VISCOSITY##PASCAL_SECONDS"},
                {"UT_Piping_Volume","##PIPING_VOLUME##LITERS"},
                {"UT_Pulsation","##PULSATION##RADIANS_PER_SECOND"},
                {"UT_Reinforcement_Area","##REINFORCEMENT_AREA##SQUARE_CENTIMETERS"},
                {"UT_Reinforcement_Area_per_Unit_Length","##REINFORCEMENT_AREA_PER_UNIT_LENGTH##SQUARE_CENTIMETERS_PER_METER"},
                {"UT_Reinforcement_Cover","##REINFORCEMENT_COVER##MILLIMETERS"},
                {"UT_Reinforcement_Length","##REINFORCEMENT_LENGTH##MILLIMETERS"},
                {"UT_Reinforcement_Spacing","##REINFORCEMENT_SPACING##MILLIMETERS"},
                {"UT_Reinforcement_Volume","##REINFORCEMENT_VOLUME##CUBIC_CENTIMETERS"},
                {"UT_Rotation","##ROTATION##RADIANS"},
                {"UT_Section_Area","##SECTION_AREA##SQUARE_CENTIMETERS"},
                {"UT_Section_Dimension","##SECTION_DIMENSION##CENTIMETERS"},
                {"UT_Section_Modulus","##SECTION_MODULUS##CUBIC_CENTIMETERS"},
                {"UT_Section_Property","##SECTION_PROPERTY##CENTIMETERS"},
                {"UT_Slope","##SLOPE##SLOPE_DEGREES"},
                {"UT_Speed","##SPEED##KILOMETERS_PER_HOUR"},
                {"UT_Stress","##STRESS##MEGAPASCALS"},
                {"UT_Structural_Frequency","##STRUCTURAL_FREQUENCY##HERTZ"},
                {"UT_Structural_Velocity","##VELOCITY##METERS_PER_SECOND"},
                {"UT_Surface_Area","##SURFACE_AREA##SQUARE_METERS_PER_METER"},
                {"UT_ThermalExpansion","##THERMAL_EXPANSION_COEFFICIENT##INVERSE_DEGREES_CELSIUS"},
                {"UT_TimeInterval","##TIMEINTERVAL##SECONDS"},
                {"UT_UnitWeight","##UNIT_WEIGHT##KILONEWTONS_PER_CUBIC_METER"},
                {"UT_Volume","##VOLUME##CUBIC_METERS"},
                {"UT_Warping_Constant","##WARPING_CONSTANT##CENTIMETERS_TO_THE_SIXTH_POWER"},
                {"UT_Weight","##WEIGHT##KILONEWTONS"},
                {"UT_Weight_per_Unit_Length","##WEIGHT_PER_UNIT_LENGTH##KILOGRAMS_FORCE_PER_METER"},
                {"UT_WireSize","##WIRE_SIZE##MILLIMETERS"}


            };
            return dict;
        }
        public static Dictionary<string, string> GetDictionaryToConvertParamTypeInSizeTableHeaderString2023()
        {
            return new Dictionary<string, string>()
            {
                { "YesNo", "##OTHER##" },
                { "WireDiameter", "##WIRE_SIZE##MILLIMETERS" },
                { "WeightPerUnitLength", "##WEIGHT_PER_UNIT_LENGTH##KILOGRAMS_FORCE_PER_METER" },
                { "Weight", "##WEIGHT##KILONEWTONS" },
                { "Wattage", "##ELECTRICAL_WATTAGE##WATTS" },
                { "WarpingConstant", "##WARPING_CONSTANT##CENTIMETERS_TO_THE_SIXTH_POWER" },
                { "Volume", "##VOLUME##CUBIC_METERS" },
                { "Url", "##OTHER##" },
                { "UnitWeight", "##UNIT_WEIGHT##KILONEWTONS_PER_CUBIC_METER" },
                { "Time", "##TIMEINTERVAL##SECONDS" },
                { "ThermalResistance", "##HVAC_THERMAL_RESISTANCE##SQUARE_METER_KELVINS_PER_WATT" },
                { "ThermalMass", "##HVAC_THERMAL_MASS##KILOJOULES_PER_KELVIN" },
                { "ThermalGradientCoefficientForMoistureCapacity", "##HVAC_THERMAL_GRADIENT_COEFFICIENT_FOR_MOISTURE_CAPACITY##KILOGRAMS_PER_KILOGRAM_KELVIN" },
                { "ThermalExpansionCoefficient", "##THERMAL_EXPANSION_COEFFICIENT##INVERSE_DEGREES_CELSIUS" },
                { "ThermalConductivity", "##HVAC_THERMAL_CONDUCTIVITY##WATTS_PER_METER_KELVIN" },
                { "Text", "##OTHER##" },
                { "SurfaceAreaPerUnitLength", "##SURFACE_AREA##SQUARE_METERS_PER_METER" },
                { "StructuralVelocity", "##VELOCITY##METERS_PER_SECOND" },
                { "StructuralFrequency", "##STRUCTURAL_FREQUENCY##HERTZ" },
                { "Stress", "##STRESS##MEGAPASCALS" },
                { "StationingInterval", "##STATIONING_INTERVAL##METERS" },
                { "Stationing", "##STATIONING##METERS" },
                { "Speed", "##SPEED##KILOMETERS_PER_HOUR" },
                { "SpecificHeatOfVaporization", "##HVAC_SPECIFIC_HEAT_OF_VAPORIZATION##JOULES_PER_GRAM" },
                { "SpecificHeat", "##HVAC_SPECIFIC_HEAT##JOULES_PER_GRAM_DEGREE_CELSIUS" },
                { "Slope", "##SLOPE##SLOPE_DEGREES" },
                { "SiteAngle", "##SITE_ANGLE##DEGREES" },
                { "SheetLength", "##PAPER LENGTH##MILLIMETERS" },
                { "SectionProperty", "##SECTION_PROPERTY##CENTIMETERS" },
                { "SectionModulus", "##SECTION_MODULUS##CUBIC_CENTIMETERS" },
                { "SectionDimension", "##SECTION_DIMENSION##CENTIMETERS" },
                { "SectionArea", "##SECTION_AREA##SQUARE_CENTIMETERS" },
                { "RotationalPointSpringCoefficient", "##ROTATIONAL_POINT_SPRING_COEFFICIENT##KILONEWTON_METERS_PER_DEGREE" },
                { "RotationalLineSpringCoefficient", "##ROTATIONAL_LINEAR_SPRING_COEFFICIENT##KILONEWTON_METERS_PER_DEGREE_PER_METER" },
                { "RotationAngle", "##ROTATION_ANGLE##DEGREES" },
                { "Rotation", "##ROTATION##RADIANS" },
                { "ReinforcementVolume", "##REINFORCEMENT_VOLUME##CUBIC_CENTIMETERS" },
                { "ReinforcementSpacing", "##REINFORCEMENT_SPACING##MILLIMETERS" },
                { "ReinforcementLength", "##REINFORCEMENT_LENGTH##MILLIMETERS" },
                { "ReinforcementCover", "##REINFORCEMENT_COVER##MILLIMETERS" },
                { "ReinforcementAreaPerUnitLength", "##REINFORCEMENT_AREA_PER_UNIT_LENGTH##SQUARE_CENTIMETERS_PER_METER" },
                { "ReinforcementArea", "##REINFORCEMENT_AREA##SQUARE_CENTIMETERS" },
                { "Pulsation", "##PULSATION##RADIANS_PER_SECOND" },
                { "PowerPerLength", "##ELECTRICAL_POWER_PER_LENGTH##WATTS_PER_METER" },
                { "PowerPerFlow", "##HVAC_POWER_PER_FLOW##WATTS_PER_CUBIC_METER_PER_SECOND" },
                { "PointSpringCoefficient", "##POINT_SPRING_COEFFICIENT##KILONEWTONS_PER_METER" },
                { "PipingVolume", "##PIPING_VOLUME##LITERS" },
                { "PipingViscosity", "##PIPING_VISCOSITY##PASCAL_SECONDS" },
                { "PipingVelocity", "##PIPING_VELOCITY##METERS_PER_SECOND" },
                { "PipingTemperatureDifference", "##PIPING_TEMPERATURE_DIFFERENCE##CELSIUS_INTERVAL" },
                { "PipingTemperature", "##PIPING_TEMPERATURE##CELSIUS" },
                { "PipingSlope", "##PIPING_SLOPE##PERCENTAGE" },
                { "PipingRoughness", "##PIPING_ROUGHNESS##MILLIMETERS" },
                { "PipingPressure", "##PIPING_PRESSURE##PASCALS" },
                { "PipingMassPerTime", "##PIPING_MASS_PER_TIME##KILOGRAMS_PER_HOUR" },
                { "PipingMass", "##PIPE_MASS##KILOGRAMS" },
                { "PipingFriction", "##PIPING_FRICTION##PASCALS_PER_METER" },
                { "PipingDensity", "##PIPING_DENSITY##KILOGRAMS_PER_CUBIC_METER" },
                { "PipeSize", "##PIPE_SIZE##MILLIMETERS" },
                { "PipeMassPerUnitLength", "##PIPE_MASS_PER_UNIT_LENGTH##KILOGRAMS_PER_METER" },
                { "PipeInsulationThickness", "##PIPE_INSULATION_THICKNESS##MILLIMETERS" },
                { "PipeDimension", "##PIPE_DIMENSION##MILLIMETERS" },
                { "Permeability", "##HVAC_PERMEABILITY##NANOGRAMS_PER_PASCAL_SECOND_SQUARE_METER" },
                { "Period", "##PERIOD##SECONDS" },
                { "NumberOfPoles", "##OTHER##" },
                { "Number", "##OTHER##" },
                { "MultilineText", "##OTHER##" },
                { "MomentScale", "##MOMENT_SCALE##INVERSE_KILONEWTONS" },
                { "MomentOfInertia", "##MOMENT_OF_INERTIA##CENTIMETERS_TO_THE_FOURTH_POWER" },
                { "Moment", "##MOMENT##KILONEWTON_METERS" },
                { "Material", "##OTHER##" },
                { "MassPerUnitLength", "##MASS_PER_UNIT_LENGTH##KILOGRAMS_PER_METER" },
                { "MassPerUnitArea", "##MASS_PER_UNIT_AREA##KILOGRAMS_PER_SQUARE_METER" },
                { "MassDensity", "##MASS_DENSITY##KILOGRAMS_PER_CUBIC_METER" },
                { "Mass", "##MASS##KILOGRAMS" },
                { "LuminousIntensity", "##ELECTRICAL_LUMINOUS_INTENSITY##CANDELAS" },
                { "LuminousFlux", "##ELECTRICAL_LUMINOUS_FLUX##LUMENS" },
                { "Luminance", "##ELECTRICAL_LUMINANCE##CANDELAS_PER_SQUARE_METER" },
                { "LoadClassification", "##OTHER##" },
                { "LinearMomentScale", "##LINEAR_MOMENT_SCALE##METERS_PER_KILONEWTON" },
                { "LinearMoment", "##LINEAR_MOMENT##KILONEWTON_METERS_PER_METER" },
                { "LinearForceScale", "##LINEAR_FORCE_SCALE##SQUARE_METERS_PER_KILONEWTON" },
                { "LinearForce", "##LINEAR_FORCE##KILONEWTONS_PER_METER" },
                { "LineSpringCoefficient", "##LINEAR_SPRING_COEFFICIENT##KILONEWTONS_PER_SQUARE_METER" },
                { "Length", "##LENGTH##MILLIMETERS" },
                { "IsothermalMoistureCapacity", "##HVAC_ISOTHERMAL_MOISTURE_CAPACITY##CUBIC_METERS_PER_KILOGRAM" },
                { "Integer", "##OTHER##" },
                { "Illuminance", "##ELECTRICAL_ILLUMINANCE##LUX" },
                { "HvacViscosity", "##HVAC_VISCOSITY##PASCAL_SECONDS" },
                { "HvacVelocity", "##HVAC_VELOCITY##METERS_PER_SECOND" },
                { "HvacTemperatureDifference", "##HVAC_TEMPERATURE_DIFFERENCE##CELSIUS_INTERVAL" },
                { "HvacTemperature", "##HVAC_TEMPERATURE##CELSIUS" },
                { "HvacSlope", "##HVAC_SLOPE##PERCENTAGE" },
                { "HvacRoughness", "##HVAC_ROUGHNESS##MILLIMETERS" },
                { "HvacPressure", "##HVAC_PRESSURE##PASCALS" },
                { "HvacPowerDensity", "##HVAC_POWER_DENSITY##WATTS_PER_SQUARE_METER" },
                { "HvacPower", "##HVAC_POWER##WATTS" },
                { "HvacMassPerTime", "##HVAC_MASS_PER_TIME##KILOGRAMS_PER_HOUR" },
                { "HvacFriction", "##HVAC_FRICTION##PASCALS_PER_METER" },
                { "HvacEnergy", "##HVAC_ENERGY##JOULES" },
                { "HvacDensity", "##HVAC_DENSITY##KILOGRAMS_PER_CUBIC_METER" },
                { "HeatingLoadDividedByVolume", "##HVAC_HEATING_LOAD_DIVIDED_BY_VOLUME##WATTS_PER_CUBIC_METER" },
                { "HeatingLoadDividedByArea", "##HVAC_HEATING_LOAD_DIVIDED_BY_AREA##WATTS_PER_SQUARE_METER" },
                { "HeatingLoad", "##HVAC_HEATING_LOAD##WATTS" },
                { "HeatTransferCoefficient", "##HVAC_COEFFICIENT_OF_HEAT_TRANSFER##WATTS_PER_SQUARE_METER_KELVIN" },
                { "HeatGain", "##HVAC_HEAT_GAIN##WATTS" },
                { "HeatCapacityPerArea", "##HVAC_HEAT_CAPACITY_PER_AREA##KILOJOULES_PER_SQUARE_METER_KELVIN" },
                { "ForceScale", "##FORCE_SCALE##METERS_PER_KILONEWTON" },
                { "Force", "##FORCE##KILONEWTONS" },
                { "FlowPerPower", "##HVAC_FLOW_PER_POWER##CUBIC_METERS_PER_WATT_SECOND" },
                { "Flow", "##PIPING_FLOW##LITERS_PER_SECOND" },
                { "FillPattern", "##OTHER##" },
                { "Factor", "##HVAC_FACTOR##PERCENTAGE" },
                { "Energy", "##ENERGY##KILOJOULES" },
                { "ElectricalTemperatureDifference", "##ELECTRICAL_TEMPERATURE_DIFFERENCE##CELSIUS_INTERVAL" },
                { "ElectricalTemperature", "##ELECTRICAL_TEMPERATURE##CELSIUS" },
                { "ElectricalResistivity", "##ELECTRICAL_RESISTIVITY##OHM_METERS" },
                { "ElectricalPowerDensity", "##ELECTRICAL_POWER_DENSITY##WATTS_PER_SQUARE_METER" },
                { "ElectricalPower", "##ELECTRICAL_POWER##WATTS" },
                { "ElectricalPotential", "##ELECTRICAL_POTENTIAL##VOLTS" },
                { "ElectricalFrequency", "##ELECTRICAL_FREQUENCY##HERTZ" },
                { "Efficacy", "##ELECTRICAL_EFFICACY##LUMENS_PER_WATT" },
                { "DuctSize", "##HVAC_DUCT_SIZE##MILLIMETERS" },
                { "DuctLiningThickness", "##HVAC_DUCT_LINING_THICKNESS##MILLIMETERS" },
                { "DuctInsulationThickness", "##HVAC_DUCT_INSULATION_THICKNESS##MILLIMETERS" },
                { "Distance", "##DISTANCE##CENTIMETERS" },
                { "Displacement", "##DISPLACEMENT/DEFLECTION##CENTIMETERS" },
                { "Diffusivity", "##HVAC_DIFFUSIVITY##SQUARE_METERS_PER_SECOND" },
                { "DemandFactor", "##ELECTRICAL_DEMAND_FACTOR##PERCENTAGE" },
                { "Default Elevation", "##LENGTH##MILLIMETERS" },
                { "DecimalSheetLength", "##PEN SIZE##MILLIMETERS" },
                { "Current", "##ELECTRICAL_CURRENT##AMPERES" },
                { "Currency", "##CURRENCY##CURRENCY" },
                { "CrossSection", "##HVAC_CROSS_SECTION##SQUARE_MILLIMETERS" },
                { "CrackWidth", "##CRACK_WIDTH##MILLIMETERS" },
                { "CostRatePower", "##ELECTRICAL_COST_RATE_POWER##COST_PER_WATT" },
                { "CostRateEnergy", "##ELECTRICAL_COST_RATE_ENERGY##COST_PER_WATT_HOUR" },
                { "CostPerArea", "##COST_PER_AREA##COST_PER_SQUARE_METER" },
                { "CoolingLoadDividedByVolume", "##HVAC_COOLING_LOAD_DIVIDED_BY_VOLUME##WATTS_PER_CUBIC_METER" },
                { "CoolingLoadDividedByArea", "##HVAC_COOLING_LOAD_DIVIDED_BY_AREA##WATTS_PER_SQUARE_METER" },
                { "CoolingLoad", "##HVAC_COOLING_LOAD##WATTS" },
                { "ConduitSize", "##CONDUIT_SIZE##MILLIMETERS" },
                { "ColorTemperature", "##COLOR_TEMPERATURE##KELVIN" },
                { "CableTraySize", "##CABLETRAY_SIZE##MILLIMETERS" },
                { "BarDiameter", "##BAR_DIAMETER##MILLIMETERS" },
                { "AreaSpringCoefficient", "##AREA_SPRING_COEFFICIENT##KILONEWTONS_PER_CUBIC_METER" },
                { "AreaForceScale", "##AREA_FORCE_SCALE##CUBIC_METERS_PER_KILONEWTON" },
                { "AreaForce", "##AREA_FORCE##KILONEWTONS_PER_SQUARE_METER" },
                { "AreaDividedByHeatingLoad", "##HVAC_AREA_DIVIDED_BY_HEATING_LOAD##SQUARE_METERS_PER_KILOWATT" },
                { "AreaDividedByCoolingLoad", "##HVAC_AREA_DIVIDED_BY_COOLING_LOAD##SQUARE_METERS_PER_KILOWATT" },
                { "Area", "##AREA##SQUARE_METERS" },
                { "ApparentPowerDensity", "##ELECTRICAL_APPARENT_POWER_DENSITY##VOLT_AMPERES_PER_SQUARE_METER" },
                { "ApparentPower", "##ELECTRICAL_APPARENT_POWER##VOLT_AMPERES" },
                { "AngularSpeed", "##HVAC_ANGULAR_SPEED##REVOLUTIONS_PER_MINUTE" },
                { "Angle", "##ANGLE##DEGREES" },
                { "AirFlowDividedByVolume", "##HVAC_AIRFLOW_DIVIDED_BY_VOLUME##LITERS_PER_SECOND_CUBIC_METER" },
                { "AirFlowDividedByCoolingLoad", "##HVAC_AIRFLOW_DIVIDED_BY_COOLING_LOAD##LITERS_PER_SECOND_KILOWATT" },
                { "AirFlowDensity", "##HVAC_AIRFLOW_DENSITY##LITERS_PER_SECOND_SQUARE_METER" },
                { "AirFlow", "##HVAC_AIR_FLOW##LITERS_PER_SECOND" },
                { "Acceleration", "##ACCELERATION##METERS_PER_SECOND_SQUARED" }

            };
        }
        // csharpier-ignore-end
    }
}
